### ISSUE TITLE
`TestSimpleReducePipelineFailOverUsingWAL` test keeps failing

### ISSUE THREAD

**Issue by vigith** [numaproj/numaflow#408] opened 2022-12-05 17:33 UTC
@xdevxy `TestSimpleReducePipelineFailOverUsingWAL` test keeps failing, I have increased the number of input messages, but I am not sure if that will fix the issue. Can you please check?

```
{"level":"error","ts":1670256555.6943505,"logger":"numaflow.Sink-processor","caller":"fetch/processor_manager.go:244","msg":"Unable to find the processor","vertex":"even-odd-sum-sink","processorEntity":"even-odd-sum-compute-sum-0","stacktrace":"github.com/numaproj/numaflow/pkg/watermark/fetch.(*ProcessorManager).startTimeLineWatcher\n\t/home/runner/work/numaflow/numaflow/pkg/watermark/fetch/processor_manager.go:244"}
{"level":"info","ts":1670256555.9443743,"logger":"numaflow.Sink-processor","caller":"fetch/processor_manager.go:184","msg":"v.AddProcessor successfully added a new fromProcessor","vertex":"even-odd-sum-sink","fromProcessor":"even-odd-sum-compute-sum-0"}
{"level":"info","ts":1670256556.6664329,"logger":"numaflow.Sink-processor","caller":"fetch/processor_manager.go:184","msg":"v.AddProcessor successfully added a new fromProcessor","vertex":"even-odd-sum-sink","fromProcessor":"even-odd-sum-compute-sum-1"}
    reduce_test.go:191: Expected vertex "sink" pod log doesn't contain "Payload -  38"
    panic.go:522: Terminating port-forward for POD even-odd-sum-in-0-xaivo
    panic.go:522: Deleting Pipeline even-odd-sum
```

_Originally posted by @yhl25 in https://github.com/numaproj/numaflow/pull/386#discussion_r1039813639_

**Comment by xdevxy** [comment] 2022-12-11 08:00
@yhl25 I cannot reproduce this as I tested with the original number of inputs and didn't see any errors either on my local runs or the remote ones. https://github.com/numaproj/numaflow/actions/runs/3667931275/jobs/6200715594. Wondering do you see the error on your local runs and can you try again on your side? cc @vigith

**Comment by yhl25** [comment] 2022-12-11 15:40
I didn't see this error in my local run, it was in one of the remote runs and it is random and very rare

**Comment by xdevxy** [comment] 2022-12-12 01:30
Hmm, the only thing that I can think of that can cause this kind of behavior is the sink vertex may not getting the output yet which matches with the change you made to make it less flaky (increase the input numbers of the input vertex). But this issue exist with all other tests within this test suite as well.

> I didn't see this error in my local run, it was in one of the remote runs and it is random and very rare

**Comment by yhl25** [comment] 2022-12-12 02:28
> Hmm, the only thing that I can think of that can cause this kind of behavior is the sink vertex may not getting the output yet which matches with the change you made to make it less flaky (increase the input numbers of the input vertex). But this issue exist with all other tests within this test suite as well.
> 
> > I didn't see this error in my local run, it was in one of the remote runs and it is random and very rare

yeah

**Comment by yhl25** [comment] 2022-12-12 02:29
https://github.com/numaproj/numaflow/actions/runs/3667931275/jobs/6203652212
I ran the e2e reduce tests in your pr, it failed.
https://github.com/numaproj/numaflow/actions/runs/3667931275/jobs/6203652212

**Comment by xdevxy** [comment] 2022-12-12 20:14
> I ran the e2e reduce tests in your pr, it failed. https://github.com/numaproj/numaflow/actions/runs/3667931275/jobs/6203652212

yeah, I guess for now, we can keep it the way it is for the reason I mentioned. In future, if it is still flaky we may want to add delay between input generation and output verification. So close this ticket, please reopen if needed.

**Closed by xdevxy** 2022-12-12 20:14 UTC
Labels: testing
