### ISSUE TITLE
spec.fromEdges.conditions in body must be of type object: null

### ISSUE THREAD

**Issue by Hughen** [numaproj/numaflow#1052] opened 2023-09-15 11:27 UTC
**Describe the bug**
```shell
kubectl apply -f https://raw.githubusercontent.com/numaproj/numaflow/stable/examples/1-simple-pipeline.yaml
```
After deploying numaflow according to the quick start documentation, the following error occurred when creating the simple pipeline.
```log
{"level":"error","ts":"2023-09-15T11:19:59.321555196Z","logger":"numaflow.controller-manager","caller":"pipeline/controller.go:83","msg":"Reconcile error","namespace":"test","pipeline":"simple-pipeline","error":"failed to create vertex, err: Vertex.numaflow.numaproj.io \"simple-pipeline-in\" is invalid: spec.toEdges.conditions: Invalid value: \"null\": spec.toEdges.conditions in body must be of type object: \"null\"","stacktrace":"github.com/numaproj/numaflow/pkg/reconciler/pipeline.(*pipelineReconciler).Reconcile\n\t/home/runner/work/numaflow/numaflow/pkg/reconciler/pipeline/controller.go:83\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:122\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:323\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:235"}
{"level":"error","ts":"2023-09-15T11:20:09.574485207Z","logger":"numaflow.controller-manager","caller":"pipeline/controller.go:83","msg":"Reconcile error","namespace":"test","pipeline":"simple-pipeline","error":"failed to create vertex, err: Vertex.numaflow.numaproj.io \"simple-pipeline-in\" is invalid: spec.toEdges.conditions: Invalid value: \"null\": spec.toEdges.conditions in body must be of type object: \"null\"","stacktrace":"github.com/numaproj/numaflow/pkg/reconciler/pipeline.(*pipelineReconciler).Reconcile\n\t/home/runner/work/numaflow/numaflow/pkg/reconciler/pipeline/controller.go:83\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:122\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:323\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:235"}
{"level":"error","ts":"2023-09-15T11:20:30.066992497Z","logger":"numaflow.controller-manager","caller":"pipeline/controller.go:83","msg":"Reconcile error","namespace":"test","pipeline":"simple-pipeline","error":"failed to create vertex, err: Vertex.numaflow.numaproj.io \"simple-pipeline-in\" is invalid: spec.toEdges.conditions: Invalid value: \"null\": spec.toEdges.conditions in body must be of type object: \"null\"","stacktrace":"github.com/numaproj/numaflow/pkg/reconciler/pipeline.(*pipelineReconciler).Reconcile\n\t/home/runner/work/numaflow/numaflow/pkg/reconciler/pipeline/controller.go:83\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:122\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:323\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:235"}
{"level":"error","ts":"2023-09-15T11:21:11.039692992Z","logger":"numaflow.controller-manager","caller":"pipeline/controller.go:83","msg":"Reconcile error","namespace":"test","pipeline":"simple-pipeline","error":"failed to create vertex, err: Vertex.numaflow.numaproj.io \"simple-pipeline-out\" is invalid: spec.fromEdges.conditions: Invalid value: \"null\": spec.fromEdges.conditions in body must be of type object: \"null\"","stacktrace":"github.com/numaproj/numaflow/pkg/reconciler/pipeline.(*pipelineReconciler).Reconcile\n\t/home/runner/work/numaflow/numaflow/pkg/reconciler/pipeline/controller.go:83\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:122\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:323\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/internal/controller/controller.go:235"}
```

**To Reproduce**

after deploy from https://numaflow.numaproj.io/quick-start/ ...

**Environment (please complete the following information):**

- Kubernetes: [v1.17.9]
- Numaflow: [v0.10.1]

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We often sort issues this way to know what to prioritize.

**Comment by syayi** [comment] 2023-09-15 18:58
@Hughen we are unable to reproduce the issue, one thing we suspect could be the K8s version, can you try with the latest stable release?

**Comment by Hughen** [comment] 2023-09-18 03:42
I added a debug log before [reconcile](https://github.com/numaproj/numaflow/blob/main/pkg/reconciler/pipeline/controller.go#L81) and found nothing wrong.
```go
plCopy := pl.DeepCopy()
ctx = logging.WithLogger(ctx, log)
log.Infow("-------debug pipelineReconciler", zap.Any("pipeline", *plCopy))
result, reconcileErr := r.reconcile(ctx, plCopy)
if reconcileErr != nil {
	log.Errorw("Reconcile error", zap.Error(reconcileErr))
}
```

debug log:
```text
{"level":"info","ts":"2023-09-18T03:35:10.759343586Z","logger":"numaflow.controller-manager","caller":"pipeline/controller.go:81","msg":"-------debug pipelineReconciler","namespace":"test","pipeline":"simple-pi$eline","pipeline":{"kind":"Pipeline","apiVersion":"numaflow.numaproj.io/v1alpha1","metadata":{"name":"simple-pipeline","namespace":"test","selfLink":"/apis/numaflow.numaproj.io/v1alpha1/namespaces/test/pipelines/simple-pipeline","uid":"652aab49-a37b-420c-9ddd-8f812eb46040","resourceVersion":"696684949","generation":1,"creationTimestamp":"2023-09-18T03:35:05Z"},"spec":{"vertices":[{"name":"in","source":{"generator":{"rpu":5,"duration":"1s","msgSize":8,"keyCount":5,"value":5}},"scale":{}},{"name":"cat","udf":{"container":null,"builtin":{"name":"cat"},"groupBy":null},"scale":{}},{"name":"out","sink":{"log":{}},"scale":{}}],"edges":[{"from":"in","to":"cat","conditions":null},{"from":"cat","to":"out","conditions":null}],"lifecycle":{"deleteGracePeriodSeconds":30,"desiredPhase":"Running"},"limits":{"readBatchSize":500,"bufferMaxLength":30000,"bufferUsageLimit":80,"readTimeout":"1s"},"watermark":{"maxDelay":"0s"}},"status":{"lastUpdated":null}}}
```

What I am confused about is that the cause of the error is the `spec.toEdges.conditions` field, but this field is not defined in the pipeline.
Where does this error come from?

**Comment by whynowy** [comment] 2023-09-18 04:05
> I added a debug log before [reconcile](https://github.com/numaproj/numaflow/blob/main/pkg/reconciler/pipeline/controller.go#L81) and found nothing wrong.
> 
> ```go
> plCopy := pl.DeepCopy()
> ctx = logging.WithLogger(ctx, log)
> log.Infow("-------debug pipelineReconciler", zap.Any("pipeline", *plCopy))
> result, reconcileErr := r.reconcile(ctx, plCopy)
> if reconcileErr != nil {
> 	log.Errorw("Reconcile error", zap.Error(reconcileErr))
> }
> ```
> 
> debug log:
> 
> ```
> {"level":"info","ts":"2023-09-18T03:35:10.759343586Z","logger":"numaflow.controller-manager","caller":"pipeline/controller.go:81","msg":"-------debug pipelineReconciler","namespace":"test","pipeline":"simple-pi$eline","pipeline":{"kind":"Pipeline","apiVersion":"numaflow.numaproj.io/v1alpha1","metadata":{"name":"simple-pipeline","namespace":"test","selfLink":"/apis/numaflow.numaproj.io/v1alpha1/namespaces/test/pipelines/simple-pipeline","uid":"652aab49-a37b-420c-9ddd-8f812eb46040","resourceVersion":"696684949","generation":1,"creationTimestamp":"2023-09-18T03:35:05Z"},"spec":{"vertices":[{"name":"in","source":{"generator":{"rpu":5,"duration":"1s","msgSize":8,"keyCount":5,"value":5}},"scale":{}},{"name":"cat","udf":{"container":null,"builtin":{"name":"cat"},"groupBy":null},"scale":{}},{"name":"out","sink":{"log":{}},"scale":{}}],"edges":[{"from":"in","to":"cat","conditions":null},{"from":"cat","to":"out","conditions":null}],"lifecycle":{"deleteGracePeriodSeconds":30,"desiredPhase":"Running"},"limits":{"readBatchSize":500,"bufferMaxLength":30000,"bufferUsageLimit":80,"readTimeout":"1s"},"watermark":{"maxDelay":"0s"}},"status":{"lastUpdated":null}}}
> ```
> 
> What I am confused about is that the cause of the error is the `spec.toEdges.conditions` field, but this field is not defined in the pipeline. Where does this error come from?

The field is defined in the `Vetex` spec.

Are you still running k8s `v1.17.9`? If you don't mind, could you try it with a cluster with a newer version?

**Comment by Hughen** [comment] 2023-09-18 04:29
Yes，k8s is v1.17.9.
Upgrading it is too difficult because in a production environment.

Is there any other way? Is there something wrong with the CRD of `Vertex`, but I didn’t see any logs about the vertex controller.

**Comment by whynowy** [comment] 2023-09-18 05:56
> Yes，k8s is v1.17.9. Upgrading it is too difficult because in a production environment.
> 
> Is there any other way? Is there something wrong with the CRD of `Vertex`, but I didn’t see any logs about the vertex controller.

From the log you posted, it happened at the time of creating Vertex objects in the pipeline controller. 

I assume you installed the CRD with `kubectl apply -n numaflow-system -f https://raw.githubusercontent.com/numaproj/numaflow/stable/config/install.yaml`, did you see any issue when running it? (I suspect there's something unsupported in the old version). 

If it's not easy for you to try with a newer k8s cluster, another option you can try is to use the simplified CRD - https://github.com/numaproj/numaflow/blob/main/config/advanced-install/minimal-crds.yaml.

**Comment by Hughen** [comment] 2023-09-18 06:37
You are right, vertex can be started normally with minimal crd.
So this is a bug?

**Comment by whynowy** [comment] 2023-09-18 07:10
> You are right, vertex can be started normally with minimal crd. So this is a bug?

I would not consider it as a bug - v1.17.9 is way behind the latest k8s version, the incompatibility is expected from K8s community. I strongly suggest you to upgrade your k8s version to benefit from new features.

**Comment by whynowy** [comment] 2023-11-02 17:37
Close it for now. Please reopen or create a new one if needed.

**Closed by whynowy** 2023-11-02 17:37 UTC
Labels: bug, can not reproduce
