### ISSUE TITLE
Performance analysis on map vertices

### ISSUE THREAD

**Issue by whynowy** [numaproj/numaflow#466] opened 2023-01-12 07:11 UTC
# Summary

As a data processing platform, we always want to make the data processing as efficient as possible. So we expect some performance analysis on the vertex pod, to figure out if there's any inefficient processing logic in the code, as well as the potential solutions for improvement.

The output of this issue would be a number of follow-up issues for the improvement tracking.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by vigith** [comment] 2023-03-24 16:44
Duplicate of #609

**Closed by vigith** 2023-03-24 16:44 UTC
Labels: enhancement, performance
